GovStackWorkingGroup/testing-webapp

.circleci/config.yml
__tests__/index.test.tsx
jest.config.js
jest.setup.js
package.json
yarn.lock

* Set up CircleCI (install, lint, test)
* Set up a sample Jest test

CircleCI project set up (includes a sample test)

---

docker-compose.yml
server/db/conn.js
server/db/jsonSchema.js
server/db/reportSchemaValidation.js
server/package.json
server/reportSave/handleSaveRequest.js
server/reportSave/utils/dataAggregation.js
server/reportSave/utils/dataModels.js
server/reportSave/utils/propertyNames.js
server/reportSave/utils/testCaseBuilder.js
server/routes/record.js
server/server.js
server/yarn.lock

Ticket: [TECH-215](https://govstack-global.atlassian.net/browse/TECH-215)
[TECH-215]: https://govstack-global.atlassian.net/browse/TECH-215?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

TECH-215: Add mongoDB schema for test report 

---

components/header/Header.less
components/mainLayout/MainLayout.less

HotFix: Changed imports paths name

HotFix: Changed imports paths name

---

__tests__/components/table/ProductTableRow.test.tsx
__tests__/components/table/__snapshots__/ProductTable.test.tsx.snap
__tests__/components/table/__snapshots__/ProductTableRow.test.tsx.snap
components/table/ProductTable.less
components/table/ProductTableRow.tsx

**Description**
Add "Last update" column to the Products table
Ticket: https://govstack-global.atlassian.net/browse/TECH-315

TECH-315: Add "Last update" column to the Products table

---

Dockerfile
server/Dockerfile
server/src/db/connection.js

Had to be done to get this deployed using Docker.
* Fix directory structure for server
* Fix type in error message
* Fix that yarn/npm installs run after source files are copied

Fix Dockerfiles

---

__tests__/components/InfiniteScrollLoader.test.tsx
__tests__/components/__snapshots__/InfiniteScrollLoader.test.tsx.snap
__tests__/components/table/__snapshots__/ProductTable.test.tsx.snap
components/InfiniteScrollLoader.tsx
components/table/ProductTable.less
components/table/ProductTable.tsx
components/table/SubTable.less
package.json
pages/_app.tsx
service/mockedData.ts
translations/en.ts
yarn.lock

Add infinite scroll to the Products table.
Ticket: https://govstack-global.atlassian.net/browse/TECH-317

TECH-317: Add infinite scroll to the Products table

---

.circleci/config.yml
deployment/deploy.sh
deployment/run-prod.sh

We continue to use a git based deployment for now. We only deploy from the main branch.
How the deployment works:
* Updates the git repo on the server
* Runs the environment without dev volume mounts (we do not use the override file)

TECH-454: Automated webapp deployment

---

jest.config.js
server/__tests__/routes.test.js
server/package.json
server/server.js
server/yarn.lock

Added test configuration for BE with simple test
**Description**:
We need to add a test configuration for BE.
Acceptance criteria:
-     Jest is used for BE tests
-     BE configuration is separate from FE configuration (Jest is added in /server/)
-     Tests are executed only once, FE doesn’t execute BE tests, and vice versa
**TICKET**: https://govstack-global.atlassian.net/browse/TECH-517

TECH-517: Add configuration for testing (BE)

---

__tests__/components/TestSummary.test.tsx
__tests__/components/__snapshots__/TestSummary.test.tsx.snap
__tests__/components/table/SubTableRow.test.tsx
__tests__/components/table/__snapshots__/SubTable.test.tsx.snap
__tests__/components/table/__snapshots__/SubTableRow.test.tsx.snap
__tests__/pages/[productName]/[buildingBlock]/[bbId].test.tsx
components/LoadingBar.less
components/LoadingBar.tsx
components/TestSummary.less
components/TestSummary.tsx
components/mainLayout/MainLayout.less
components/table/BuildingBlocksImage.tsx
components/table/ProductTableRow.tsx
components/table/SubTable.less
components/table/SubTable.tsx
components/table/SubTableRow.tsx
pages/[productName]/[bbId].tsx
pages/[productName]/[buildingBlock]/[bbId].tsx
pages/_app.tsx
service/serviceAPI.ts
service/types.ts
styles/Globals.less
styles/Variables.less
translations/en.ts

Add Results Page
Ticket: https://govstack-global.atlassian.net/browse/TECH-414
https://user-images.githubusercontent.com/80507519/227266814-ed7ece79-30a3-4510-9d82-6900831280ae.mov
------------------------------
- with animated loading bar
https://user-images.githubusercontent.com/80507519/227267220-e77e36ae-49ae-4260-ad77-18f5830c21cb.mov

TECH-414: Add Results Page

---

__tests__/components/TestStepsView.test.tsx
__tests__/components/__snapshots__/TestStepsView.test.tsx.snap
__tests__/components/table/TestResultTable.test.tsx
__tests__/components/table/TestResultTableRow.test.tsx
__tests__/components/table/__snapshots__/TestResultTable.test.tsx.snap
__tests__/components/table/mockedData/ProductTable.ts
components/TestStepsView.less
components/TestStepsView.tsx
components/TestSummary.less
components/header/Header.less
components/table/ProductTable.less
components/table/SubTable.less
components/table/TestResultTable.less
components/table/TestResultTable.tsx
components/table/TestResultTableRow.tsx
pages/[productName]/[buildingBlock]/[bbId].tsx
pages/_app.tsx
service/types.ts
styles/Globals.less
styles/Variables.less
translations/en.ts

Ticket: https://govstack-global.atlassian.net/browse/TECH-416
https://user-images.githubusercontent.com/80507519/229077393-147018fd-b971-4d53-93c0-704571859ee7.mov

TECH-416: Add Test details component

---

.eslintrc
__tests__/components/table/ProductTableRow.test.tsx
__tests__/components/table/TestResultTableRow.test.tsx
components/table/ProductTableRow.tsx
components/table/TestResultTable.tsx
package.json
yarn.lock

Fix eslint configuration on FE.
Ticket: https://govstack-global.atlassian.net/browse/TECH-535

TECH-535: Fix eslint configuration on FE

---

server/src/db/repositories/reportRepository.js

Fixed repeated incoming data and added uri to the response.
TICKET: https://govstack-global.atlassian.net/browse/TECH-533

Tech 533: Fix /report/:id endpoint

---

server/src/db/repositories/reportRepository.js

Added uri field and fixed repeated data in the response object for report/id endpoint
TICKET: https://govstack-global.atlassian.net/browse/TECH-533

TECH-533: Fix /report/:id endpoint

---

components/shared/SearchInput.less
components/shared/SearchInput.tsx
package.json
pages/_app.tsx
styles/Globals.less
styles/Variables.less
translations/en.ts
yarn.lock

Add autocomplete for Software search (FE)
Ticket: https://govstack-global.atlassian.net/browse/TECH-514

TECH-514: Add autocomplete for Software search (FE)

---

server/src/db/pipelines/reportDetails.js

Add product metadata in details compatibilities section.

TECH-456: Include product Meta in the report detail payload

---

__tests__/components/table/TestResultTable.test.tsx
__tests__/components/table/TestResultTableHeader.test.tsx
__tests__/components/table/__snapshots__/TestResultTable.test.tsx.snap
__tests__/components/table/__snapshots__/TestResultTableHeader.test.tsx.snap
components/table/ProductTable.less
components/table/TestResultTable.less
components/table/TestResultTable.tsx
components/table/TestResultTableHeader.tsx
components/table/types.ts
pages/[productName]/[buildingBlock]/[bbId].tsx
service/serviceAPI.ts

Add sorting to the Result table.
Ticket: https://govstack-global.atlassian.net/browse/TECH-420
https://user-images.githubusercontent.com/80507519/232028561-e4ecf705-8cac-4e41-b5b4-21ca049632c2.mov

TECH-420: Add sorting to the Result table

---

server/src/db/pipelines/latestReports.js
server/src/useCases/report/productCompatibility/handleGetProductRequest.js

Added missing sort field requirement for [TECH-417](https://govstack-global.atlassian.net/browse/TECH-417).
[TECH-417]: https://govstack-global.atlassian.net/browse/TECH-417?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

TECH-417: Added missing filtering option

---

__tests__/components/table/ProductTable.test.tsx
__tests__/components/table/ProductTableHeader.test.tsx
__tests__/components/table/ProductTableRow.test.tsx
__tests__/components/table/__snapshots__/ProductTable.test.tsx.snap
__tests__/components/table/__snapshots__/ProductTableHeader.test.tsx.snap
__tests__/components/table/__snapshots__/ProductTableRow.test.tsx.snap
__tests__/components/table/mockedData/ProductTable.ts
components/table/ProductTable.less
components/table/ProductTable.tsx
components/table/ProductTableHeader.tsx
components/table/ProductTableRow.tsx
components/table/TestResultTableHeader.tsx
components/table/types.ts
service/serviceAPI.ts
service/types.ts

Add sorting to the Product table.
Ticket: https://govstack-global.atlassian.net/browse/TECH-418
https://user-images.githubusercontent.com/80507519/231485431-f6ef31a6-4f03-4c1e-bed3-54a518343f48.mov

TECH-418: Add sorting to the Product table

---

server/package.json
server/src/controllers/controllerUtils.js
server/src/controllers/reportController.js
server/src/useCases/report/productTestCases/handleGetProductDetailsRequest.js
server/src/useCases/report/reportSave/handleSaveRequest.js
server/yarn.lock

TICKET: [TECH-656](https://govstack-global.atlassian.net/browse/TECH-656)
Python doesn't support cucumber message format. This PR adds functionality that checks (by comparing first character in file with square bracket) if given input is JSON Array (True) instead of NDJSON format (False). 
[TECH-656]: https://govstack-global.atlassian.net/browse/TECH-656?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

TECH-656: Handle JSON format in report save request

---

deployment/run-prod.sh
docker-compose.prod.yml
docker-compose.yml

ticket: https://govstack-global.atlassian.net/browse/TECH-683

TECH-683: Generate SSL certificate

---

.circleci/config.yml
.circleci/ssh-config
deployment/deploy.sh

Adding settings when selecting a server depending on the branch

Settings for server selection

---

.circleci/config.yml
.circleci/ssh-config

Setting the address for the appropriate server depending on the branch

Address setting for the server

---

README.md

Ticket:
https://govstack-global.atlassian.net/browse/TECH-909
Changes:
- README documentation is updated with Git Flow guidelines

TECH-909: Update README.md

---

README.md
src/__tests__/components/header/HeaderMenuButton.test.tsx
src/__tests__/components/header/__snapshots__/Header.test.tsx.snap
src/__tests__/components/header/__snapshots__/HeaderMenuButton.test.tsx.snap
src/__tests__/components/mainLayout/__snapshots__/MainLayout.test.tsx.snap
src/components/header/Header.less
src/components/header/Header.tsx
src/components/header/HeaderMenuButton.less
src/components/header/HeaderMenuButton.tsx
src/pages/_app.tsx
src/pages/softwareComplianceTesting/index.tsx
src/styles/Globals.less
src/styles/Variables.less
src/translations/en.ts

Ticket : https://govstack-global.atlassian.net/browse/TECH-864

TECH-864: Add nav bar menu to Testing Webapp

---

backend/Dockerfile

Changes:
- matched dockerfile version for ndoe in backend

changed backend dockerfile to match node version

---

backend/@types/index.d.ts
backend/src/db/pipelines/compliance/complianceListAggregation.ts
backend/src/db/pipelines/compliance/formDetailAggregation.ts
backend/src/db/pipelines/compliance/softwareDetailAggregation.ts
backend/src/db/repositories/complianceRepository.ts
backend/src/useCases/compliance/handleGetAllComplianceReports.ts

Changes:
1. Added a "count" value to the pipeline for aggregating the compliance list.
2. Moved pipelines to separate files.
Example output:

TECH-869: added count to the pipeline

---

backend/src/db/pipelines/compliance/complianceListAggregation.ts

Changes:
- fixed pagination
- added sample sorting for development

TECH-869: fixed pagination and added sample sorting

---

frontend/components/compliance/EvaluationSchemaTable.tsx

Ticket: https://govstack-global.atlassian.net/browse/TECH-875

TECH-875: Evaluation schema

---

backend/src/db/schemas/compliance.ts

**Changes:**
1. Deployment compliance is now represented at the software information level, not solely at the building block level. It includes documentation, deployment instructions (previously named "container link"), and a list of requirements for deployment, each paired with a compliance level indicator (0, 1, or 2).
2. Deployment compliance at the building block level has been streamlined to include only an "isCompliant" field with a boolean value (true/false).
3. A description field for software added

Changed deployment compliance

---

backend/src/useCases/compliance/handleCreateDraft.ts

Changed draft link to valid link
Example output:

Changed draft link to valid link

---

backend/src/db/pipelines/compliance/softwareDetailAggregation.ts

Ticket:
https://govstack-global.atlassian.net/browse/TECH-988
Changes:
- deployment compliance is added to each bb for software detail endpoint
Output data now includes also:

TECH-988: added deployment compliance into software details endpoint

---

frontend/components/compliance/SoftwareComplianceWith.tsx
frontend/components/table/Table.less
frontend/components/table/Table.tsx
frontend/service/types.ts
frontend/styles/Globals.less

Ticket: https://govstack-global.atlassian.net/browse/TECH-988

TECH-988: Software Compliance Detailed Report - add Deployment Compliance information

---

backend/@types/index.d.ts
backend/src/controllers/complianceController.ts
backend/src/db/pipelines/compliance/formDetailAggregation.ts
backend/src/db/repositories/complianceRepository.ts
backend/src/repositories/complianceRepository.ts
backend/src/routes/compliance.ts
backend/src/useCases/compliance/handleCreateDraft.ts
backend/src/useCases/compliance/handleGetDraftDetail.ts
backend/src/useCases/compliance/handleGetFormDetail.ts

Ticket:
https://govstack-global.atlassian.net/browse/TECH-991
Changes:
- the endpoint /compliance/forms/:id handle both formId and uniqueId in pipepline

TECH-991: change pipeline for form detail to handle uniqueId

---

frontend/components/compliance/ListOfCandidateResults.tsx
frontend/components/table/Table.less
frontend/components/table/Table.tsx

Ticket: https://govstack-global.atlassian.net/browse/TECH-993

TECH-993: Software compliance table - rows should be collapsable/expandable

---

frontend/__tests__/components/compliance/__snapshots__/EvaluationSchemaTable.test.tsx.snap
frontend/components/compliance/EvaluationSchemaTable.tsx
frontend/translations/en.ts

Ticket: https://govstack-global.atlassian.net/browse/TECH-987

TECH-987: Adjust the Deployment Compliance values in the table - checkbox should be replaced with Level 1 label

---

backend/server.ts

**Ticket:**
https://govstack-global.atlassian.net/browse/TECH-994
**Changes:**
- added access to static files for FE
It can be accessed by using url: `"host/uploads/file.ext"`
**Example:**

TECH-994: express static file added

---

frontend/components/compliance/ListOfCandidateResults.tsx
frontend/components/mainLayout/MainLayout.less
frontend/components/table/ProductTable.less
frontend/components/table/Table.less
frontend/components/table/Table.tsx
frontend/styles/Globals.less

Ticket: [Software compliance table - rows should be collapsable/expandable](https://govstack-global.atlassian.net/browse/TECH-993)
https://github.com/GovStackWorkingGroup/testing-webapp/assets/80507519/b9417d6d-8600-411e-901a-982f7e2d5c07

TECH-933: Software compliance table - rows should be collapsable/expandable

---

frontend/components/form/SoftwareAttributesForm.tsx
frontend/components/form/SoftwareComplianceForm.tsx
frontend/components/shared/DragAndDrop.tsx
frontend/components/shared/ProgressBar.tsx
frontend/pages/softwareRequirementsCompliance/form/[draftUUID]/[formStep].tsx
frontend/service/serviceAPI.ts

Ticket: https://govstack-global.atlassian.net/browse/TECH-876

TECH-876: Interface for Software Provider to Start New Draft

---

backend/src/useCases/compliance/handleCreateDraft.ts

Ticket:
https://govstack-global.atlassian.net/browse/TECH-995
Changes:
- Modified the returned link for Draft to remove "api." if it appears at the beginning of the string.

TECH-995: delete .api from Draft URL if present

---

backend/src/useCases/compliance/handleEditDraft.ts

Updated private function for creating frontend url for edited draft

Updated private function for creating frontend url for edited draft

---

backend/src/db/schemas/compliance/compliance.ts
frontend/package.json
frontend/yarn.lock

**Changes:**
- updated version of yarn lock and package json
- fix typo in compiance schema

Fix yarn lock and correct typo in compliance schema

---

backend/src/db/schemas/compliance/compliance.ts

Compliance software version is no longer a required filed since we are using only the most recent version for testing.

Version is no more required in compliance

---

backend/@types/index.d.ts
backend/package.json
backend/src/db/pipelines/compliance/complianceListAggregation.ts
backend/src/db/repositories/complianceRepository.ts
backend/src/middlewares/paginationMiddleware.ts
backend/src/repositories/complianceRepository.ts
backend/src/services/validators/complianceRequestValidators.ts
backend/src/useCases/compliance/handleGetAllComplianceReports.ts
backend/yarn.lock

TICKET: [TECH-872](https://govstack-global.atlassian.net/browse/TECH-872)
[TECH-872]: https://govstack-global.atlassian.net/browse/TECH-872?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

 TECH-872: Added handling for compliance filters - backend 

---

backend/__tests__/gitBookApi.test.ts
backend/__tests__/testData/gitBookDocumentCrossCuttingRequirements.json
backend/__tests__/testData/gitBookDocumentFunctionalRequirements.json
backend/src/config/index.ts
backend/src/db/schemas/bbRequirements.ts
backend/src/db/schemas/compliance/compliance.ts
backend/src/services/gitBookService/CollectionsManager.ts
backend/src/services/gitBookService/PageContentManager.ts
backend/src/services/gitBookService/SpacesManager.ts
backend/src/services/gitBookService/bbRequirementsProcessing.ts
backend/src/useCases/compliance/handleEditDraft.ts

Ticket:
https://govstack-global.atlassian.net/browse/TECH-986
Changes:
- added interface requirements for BBs. Each bb has got the same interface requirements.
- added tests for cross-cutting requirements
Reference:
- https://govstack.gitbook.io/specification/architecture-and-nonfunctional-requirements/5-cross-cutting-requirements

TECH-986: added interface compliance requirements to cron job

---

backend/src/db/pipelines/compliance/AllbbRequirements.ts

Changes:
- added interface compliance into the pipeline for getting requirements bb

Extended pipeline with interface compliance requirements

---

backend/src/db/schemas/compliance/compliance.ts

Added sparse property to uniqueId

Added sparse property to uniqueId

---

backend/src/config/index.ts

Rate limiter extended to 1000 request per hour

Rate limiter extended to 1000 request per hour

---

backend/src/db/pipelines/compliance/draftDetailAggregation.ts
backend/src/db/schemas/compliance/compliance.ts
frontend/components/form/SoftwareAttributesForm.tsx
frontend/components/form/SoftwareComplianceForm.tsx
frontend/components/form/helpers.tsx
frontend/components/table/IRSC/IRSCInterfaceTable.tsx
frontend/service/serviceAPI.ts
frontend/service/types.ts
frontend/translations/en.ts

Ticket: https://govstack-global.atlassian.net/browse/TECH-1009

TECH-1009: Add Software Version to the form

---

frontend/components/compliance/SoftwareComplianceWith.tsx

Error handling added for software details page

HotFix/softwareDetails: error handling added

---

frontend/.env

Overwritting value for test purpose

Overwritting value for test purpose

---

backend/src/db/pipelines/compliance/formDetailAggregation.ts

Changes:
Added deploiyment compliance to the forms detail endpoint pipeline.

Changed pipline to add compliance details

---

frontend/.gitignore
frontend/__tests__/components/header/__snapshots__/Header.test.tsx.snap
frontend/__tests__/components/mainLayout/__snapshots__/MainLayout.test.tsx.snap
frontend/components/header/Header.tsx
frontend/translations/en.ts

Ticket:
https://govstack-global.atlassian.net/browse/TECH-898
Changes:
- added logout functionality
- storage is cleared and user is redirected to the main page

Feature/tech 898: logout functionality

---

backend/@types/index.d.ts
backend/src/controllers/complianceController.ts
backend/src/db/repositories/complianceRepository.ts
backend/src/repositories/complianceRepository.ts
backend/src/routes/compliance.ts
backend/src/useCases/compliance/handleAcceptForm.ts
backend/src/useCases/compliance/handleRejectForm.ts

Ticket:
https://govstack-global.atlassian.net/jira/software/c/projects/TECH/issues/TECH-1007
Changes:
- approve form endpoint added
- reject form endpoint added
Test:
- testes functionality manually
Note:
- middleware is not yet added to the endpoint!

TECH-1007: added endpoint to reject and approve compliance forms

---

backend/src/middlewares/fileUpload.ts
backend/src/routes/compliance.ts

Ticket:
https://govstack-global.atlassian.net/browse/TECH-1014
Changes:
- multer uses more mime types to save the files

TECH-1014: change multer config to handle pdf, doc and plain text files

---

backend/@types/index.d.ts
backend/src/controllers/complianceController.ts
backend/src/db/repositories/complianceRepository.ts
backend/src/db/schemas/compliance/compliance.ts
backend/src/repositories/complianceRepository.ts
backend/src/routes/compliance.ts
backend/src/useCases/compliance/handleAcceptForm.ts
backend/src/useCases/compliance/handleRejectForm.ts
backend/src/useCases/compliance/handleUpdateForm.ts

Ticket:
https://govstack-global.atlassian.net/browse/TECH-1007
Changes:
- accept/reject endpoints also can update the data
- there is new endpoint for updating form data, only for bb level and interface/deployment compliance/requirement specification

Feature/tech 1007: review form and update level and notes for bb

---

frontend/.env.example
frontend/__tests__/components/header/__snapshots__/Header.test.tsx.snap
frontend/__tests__/components/mainLayout/__snapshots__/MainLayout.test.tsx.snap
frontend/components/header/Header.less
frontend/components/header/Header.tsx
frontend/next.config.js

Ticket:
https://govstack-global.atlassian.net/browse/TECH-957
Changes:
- help button is visible and it redirects to the Slack #testing channel

TECH-957: added help button that redirects to the Slack

---

frontend/components/compliance/SoftwareAttributes.tsx
frontend/components/compliance/SoftwareComplianceWith.tsx
frontend/components/compliance/SoftwareDetails.less
frontend/components/shared/combined/RequirementSpecificationSelectBB.tsx
frontend/components/shared/combined/SelectBBs.tsx
frontend/components/table/ComplianceDetailTable.tsx
frontend/pages/softwareRequirementsCompliance/details/[softwareName]/index.tsx
frontend/service/types.ts

TECH-903: Fixed types, render read only view for interface and requirement, added evaluation schema to the table

TECH-903: Hotfix

---

backend/.env.example
backend/src/config/index.ts
backend/src/useCases/handleGitHubLogin.ts

Ticket:
https://govstack-global.atlassian.net/browse/TECH-902
Changes:
- login now checks the Reviewers team on GH

TECH-902: added groups into the github auth

---

backend/@types/index.d.ts
backend/src/db/repositories/complianceRepository.ts
backend/src/routes/compliance.ts
frontend/pages/softwareRequirementsCompliance/details/[softwareName]/index.tsx
frontend/service/serviceAPI.ts
frontend/service/types.ts

Ticket:
https://govstack-global.atlassian.net/browse/TECH-1007
Changes:
- FE payload changed to match the designed BE payload
- BE added flag to skip checking for status when update is called from "const updateStatus"
- routing middleware for accpet/reject is disabled

TECH-1007: accept/reject fix BE, form payload fixed

---

backend/src/useCases/handleGitHubLogin.ts
frontend/pages/index.tsx
frontend/service/serviceAPI.ts
frontend/translations/en.ts

Ticket:
https://govstack-global.atlassian.net/browse/TECH-1024

Feature/tech 1024: login redirection 

---

backend/@types/index.d.ts
backend/src/db/repositories/complianceRepository.ts
backend/src/useCases/compliance/handleSubmitForm.ts

Recipient email was not defined.

Fixed submit recipients

---

frontend/components/shared/combined/RequirementSpecificationSelectBB.tsx
frontend/pages/requirements/details/[softwareName]/index.tsx

Workflow spec has no cross cutting requirements, and form was not showing functional requirements

Show requirements even if no cross cutting

---

frontend/components/compliance/SoftwareDetails.tsx

ticket: https://govstack-global.atlassian.net/browse/TECH-1048
Details: 
- Changed text with link to button with link

TECH-1048: Make the assessment detail button 'view report details' more prominent

---

backend/@types/index.d.ts
backend/src/db/pipelines/compliance/draftDetailAggregation.ts
backend/src/db/pipelines/compliance/formDetailAggregation.ts
backend/src/db/schemas/compliance/compliance.ts
frontend/components/form/EvaluationSummary.tsx
frontend/components/form/IRSForm.tsx
frontend/components/shared/combined/RequirementSpecificationSelectBB.tsx
frontend/components/table/IRSC/IRSCKeyDigitalFunctionalitiesTable.tsx
frontend/service/serviceAPI.ts
frontend/service/types.ts
frontend/translations/en.ts

https://govstack-global.atlassian.net/browse/TECH-1041
Changes:
-  Add a new section to the Requirements Specification Compliance form for KDFs
-  Show the KDF results in the requirements report
- Adjusted some return/functions to be inline
- Changed backend type name of KDF to be more consistant with others

TECH-1041: Add a new section to the Requirements Specification Compliance form for KDFs

---

frontend/components/form/IRSForm.tsx
frontend/service/types.ts

Changes:
- added missing types: KDF and _id for types

TECH-1041: fix eslint errors

---

backend/src/db/schemas/compliance/compliance.ts
backend/src/services/gitBookService/KeyDigitalFunctionalitiesExtractor.ts
backend/src/services/gitBookService/PageContentManager.ts
backend/src/services/gitBookService/bbRequirementsProcessing.ts
frontend/service/types.ts

Ticket:
https://govstack-global.atlassian.net/browse/TECH-1044
Changes:
- for each cross-cutting, interface, functional and key digital requirements there is a link saved in the database that links to anchor in gitbook (specific url)
Example:
1. Cross-Cutting link leads directly to the anchor:
2. Functional requirements are mostly (if not only) list items, so they can only redirect to the heading above them:
3. Key Digital Functionalities works the same as Cross-Cutting: 
4. And Interface Requirements are common for each bb, so they lead to the same page.
1. Manual tests for random links of each group. If there was issue it was immediately fixed.
2. It does not work for some of the requirements like for the first two anchors of …

TECH-1044: added link to gitbook for each requirement

---

backend/src/controllers/testFetchReqWithDesc.ts

test branch for loading data: to be reverted

test to be reverted

---

backend/src/routes/compliance.ts

Reverts GovStackWorkingGroup/testing-webapp#233

Revert "added test route"

---

backend/src/services/gitBookService/KeyDigitalFunctionalitiesExtractor.ts
backend/src/services/gitBookService/PageContentManager.ts

Ticket:
https://govstack-global.atlassian.net/browse/TECH-1065
Changes:
- description is now being fetched along with header of the requirement. It affects **Cross-Cutting** and **Interface** requirements
- interface requirements are increased from 6 to 26 fetched from: https://govstack.gitbook.io/specification/architecture-and-nonfunctional-requirements/5-cross-cutting-requirements 
1. Manually for GIS and Consent building blocks.
2. Manually for interface requirements
3. Created a script and test endpoint to fetch requirements for each bb, before and after changes. Compared it in the xlsx file:
[comparision-before-and-after.ods](https://github.com/user-attachments/files/15818550/comparision-before-and-after.ods)

TECH-1065: added nested search for description of requirements

---

backend/src/db/pipelines/compliance/complianceListAggregation.ts
backend/src/db/pipelines/compliance/draftDetailAggregation.ts
backend/src/db/pipelines/compliance/softwareDetailAggregation.ts
frontend/components/compliance/ListOfCandidateResults.tsx

**Ticket:**
https://govstack-global.atlassian.net/browse/TECH-1059
**Changes:**
- logged user "Reviewer" can now see drafts in forms list on the main page
- application can handle uncompleted forms and display it without breaking
**How was it tested:**
1. Draft form was created and after each update there was a test if application will handle this kind of uncompleted object. No issue occurred:
Empty requirements list:
Uncompleted requirements list:

TECH-1059: drafts are visible for reviewrs in report list

---

frontend/components/form/InterfaceCompliance.tsx
frontend/components/form/RequirementSpecificationForm.tsx
frontend/components/shared/combined/RequirementSpecificationSelectBB.tsx
frontend/components/shared/combined/SelectBBs.tsx
frontend/components/table/IRSC/IRSCCrossCuttingTable.tsx
frontend/components/table/IRSC/IRSCFunctionalTable.tsx
frontend/components/table/IRSC/IRSCInterfaceTable.tsx
frontend/components/table/IRSC/IRSCKeyDigitalFunctionalitiesTable.tsx
frontend/service/types.ts

Ticket: https://govstack-global.atlassian.net/browse/TECH-1046
Changes: 
- added summary of filled requirements (filled requirements/all requirements)
- added new flag to maintain if the from is active or not
- adjustments for code
- changed max limit of characters in comment section from 100 to 250

TECH-1046: Display the number of fulfilled requirements for each section

---

frontend/components/compliance/ReportViewDetail.tsx

ticket: https://govstack-global.atlassian.net/browse/TECH-1071
Changes: 
- Changed "Compliance" order under report details

TECH-1071: Change "Compliance" order under report details

---

frontend/__tests__/components/compliance/__snapshots__/EvaluationSchemaTable.test.tsx.snap
frontend/components/Definition.tsx
frontend/components/compliance/ListOfCandidateResultFilter.tsx
frontend/components/compliance/ListOfCandidateResults.tsx
frontend/components/compliance/SoftwareComplianceWith.tsx
frontend/components/compliance/SoftwareDetails.less
frontend/components/compliance/SoftwareDetails.tsx
frontend/components/form/EvaluationSummary.tsx
frontend/components/form/InterfaceCompliance.tsx
frontend/components/form/RequirementSpecificationForm.tsx
frontend/components/shared/buttons/BackToPageButton.tsx
frontend/components/shared/buttons/Button.tsx
frontend/components/shared/combined/RequirementSpecificationSelectBB.tsx
frontend/components/shared/inputs/Input.tsx
frontend/components/shared/inputs/MultiSelectDropdown.tsx
frontend/components/shared/inputs/Select.tsx
frontend/components/shared/modals/InfoModal.tsx
frontend/components/table/ComplianceDetailTable.tsx
frontend/components/table/Table.less
frontend/components/table/Table.tsx
frontend/hooks/useTranslation.tsx
frontend/service/types.ts
frontend/translations/en.ts

ticket: https://govstack-global.atlassian.net/browse/TECH-1051
Changes: 
- Changed detailed instructions for step 3 
- changed postion of KDF to be first
- added link for gitbook in detailed instruction
ticket: https://govstack-global.atlassian.net/browse/TECH-1052
Changes: 
- Sort the list of assessments on the home page by submission date
- added new type for format translation text
- fixed types across many files
ticket: https://govstack-global.atlassian.net/browse/TECH-1072
Changes: 
- Make Evaluation Schema more coherent
ticket: https://govstack-global.atlassian.net/browse/TECH-1074
Changes: 
- Make Levels clickable with the Evaluation Schema appearing
- added new style 'cursor-pointer'
ticket: https://govstack-global.atlassian.net/browse/TECH-1053
Changes: 
- imported and adjusted …

TECH-1051, TECH-1052, TECH-1053, TECH-1072, TECH-1074 

---

frontend/components/Definition.tsx
frontend/components/compliance/EvaluationSchemaTable.tsx
frontend/components/form/DeploymentComplianceForm.tsx
frontend/components/form/InterfaceCompliance.tsx
frontend/components/form/RequirementSpecificationForm.tsx
frontend/components/form/SoftwareAttributesForm.tsx
frontend/components/form/helpers.tsx
frontend/components/header/HeaderMenuButton.tsx
frontend/components/shared/inputs/Checkbox.tsx
frontend/components/table/Table.tsx
frontend/hooks/useTranslation.tsx
frontend/service/types.ts

This PR provides fixes for types for typescript code.

TECH-1051: eslint fixes, mostly types

---

backend/src/db/pipelines/compliance/complianceListAggregation.ts

Ticket:
https://govstack-global.atlassian.net/browse/TECH-1037
Changes:
- added logo for list endpoint
Request made with postman returns a specific logo of the software.

TECH-1037: extended pipeline to to handle logo for list endpoint

---

backend/src/services/gitBookService/bbRequirementsProcessing.ts

Ticket:
https://govstack-global.atlassian.net/browse/TECH-1039
Changes:
- added function that can handle specific naming of BB like "GIS"

TECH-1039: added function to handle specific names by bb-keys

---

backend/.env.example
backend/src/config/index.ts
backend/src/services/gitBookService/PageContentManager.ts

Ticket:
https://govstack-global.atlassian.net/browse/TECH-1056
Changes:
- add prefix as status of the requirements for cross-cutting and interface requirements

TECH-1056: status added for cross cutting and interface req

---

frontend/components/compliance/ListOfCandidateResults.tsx
frontend/components/compliance/SoftwareDetails.less
frontend/components/table/Table.tsx
frontend/service/types.ts

Ticket: https://govstack-global.atlassian.net/browse/TECH-1037
Changes: 
- Display software logos

TECH-1037: Add logo to candidates list

---

frontend/components/shared/TableCells.less
frontend/components/shared/TableCells.tsx
frontend/components/table/IRSC/IRSCCrossCuttingTable.tsx
frontend/components/table/IRSC/IRSCFunctionalTable.tsx
frontend/components/table/IRSC/IRSCInterfaceTable.tsx
frontend/components/table/IRSC/IRSCKeyDigitalFunctionalitiesTable.tsx
frontend/pages/_app.tsx
frontend/service/serviceAPI.ts
frontend/translations/en.ts

Ticket: https://govstack-global.atlassian.net/browse/TECH-1045
Changes: 
- Added text buttons with directions to GitBook
- Changed truncated text, removed old system, created a new function, now truncate should not be longer than 3 lines.

TECH-1045: Update the requirements report with links

---

backend/src/db/pipelines/compliance/softwareDetailAggregation.ts

Ticket:
https://govstack-global.atlassian.net/browse/TECH-1077

TECH-1077: added _id for detial endpoint pipeline

---

backend/src/db/pipelines/compliance/softwareDetailAggregation.ts

Ticket:
https://govstack-global.atlassian.net/browse/TECH-1077
Changes:
- changed _id to be Object id instead of name that was used for aggregation

Added object ID as _id for deletetion

---

backend/src/services/gitBookService/KeyDigitalFunctionalitiesExtractor.ts
backend/src/services/gitBookService/PageContentManager.ts
backend/src/services/gitBookService/bbRequirementsProcessing.ts

Ticket:
https://govstack-global.atlassian.net/browse/TECH-1039
Changes:
- link now redirect to public documentation instead of API.git book that was accessible only for provisioned users
- added default requirement status for KDF

1039: fixed requirements to link to public documentation

---

frontend/components/compliance/SoftwareDetails.less
frontend/components/table/IRSC/IRSCCrossCuttingTable.tsx
frontend/components/table/IRSC/IRSCFunctionalTable.tsx
frontend/components/table/IRSC/IRSCInterfaceTable.tsx
frontend/components/table/IRSC/IRSCKeyDigitalFunctionalitiesTable.tsx

Tickets:
https://govstack-global.atlassian.net/browse/TECH-1046
https://govstack-global.atlassian.net/browse/TECH-1037
Changes:
- Adjusted logo on software/report page
- Required number will not count fulfillments with status 0

TECH-1046 & TECH-1037

---

frontend/__tests__/components/compliance/__snapshots__/EvaluationSchemaTable.test.tsx.snap
frontend/__tests__/components/header/__snapshots__/Header.test.tsx.snap
frontend/__tests__/components/mainLayout/__snapshots__/MainLayout.test.tsx.snap
frontend/components/Definition.tsx
frontend/components/compliance/EvaluationSchemaTable.tsx
frontend/components/form/EvaluationSummary.tsx
frontend/components/form/InterfaceCompliance.tsx
frontend/components/shared/ProgressBar.less
frontend/pages/apiTesting/index.tsx
frontend/service/constants.ts
frontend/translations/en.ts

tickets: 
https://govstack-global.atlassian.net/browse/TECH-1049
https://govstack-global.atlassian.net/browse/TECH-1076
Changes: 
- updates to descriptions, texts
- update evaluation schema table

TECH-1076 & TECH-1049

---

frontend/components/shared/TableCells.less
frontend/components/shared/TableCells.tsx

Changes: 
- validate if the link is provided, if not do not force to display Link

Fix for rendering BB requirements

---

docker-compose.prod.yml
docker-compose.staging.yml
frontend/components/shared/TableCells.less
frontend/components/shared/TableCells.tsx

https://github.com/GovStackWorkingGroup/testing-webapp/releases/tag/24.07.02

Release 24.07.02

---

frontend/__tests__/components/compliance/__snapshots__/EvaluationSchemaTable.test.tsx.snap
frontend/__tests__/components/header/__snapshots__/Header.test.tsx.snap
frontend/__tests__/components/mainLayout/__snapshots__/MainLayout.test.tsx.snap
frontend/components/Definition.tsx
frontend/components/compliance/EvaluationSchemaTable.tsx
frontend/components/form/EvaluationSummary.tsx
frontend/components/form/InterfaceCompliance.tsx
frontend/components/form/RequirementSpecificationForm.tsx
frontend/components/shared/ProgressBar.less
frontend/pages/apiTesting/index.tsx
frontend/service/constants.ts
frontend/translations/en.ts

This reverts commit d230abc56a7f7bc253d7b4827dc026e11109aeb3.

Revert "release: revert TECH-1049, TECH-1076 because they are not in status Done

---

frontend/components/table/IRSC/IRSCCrossCuttingTable.tsx
frontend/components/table/IRSC/IRSCFunctionalTable.tsx
frontend/components/table/IRSC/IRSCInterfaceTable.tsx
frontend/components/table/IRSC/IRSCKeyDigitalFunctionalitiesTable.tsx
frontend/components/table/IRSC/IRSCTable.less
frontend/translations/en.ts

Ticket: https://govstack-global.atlassian.net/browse/TECH-1082
Changes: 
- each BB requirement Table can be folded.

TECH-1082: Fold list of requirements

---

frontend/components/shared/combined/RequirementSpecificationSelectBB.tsx
frontend/components/shared/combined/SelectBBs.tsx
frontend/components/shared/inputs/Inputs.less
frontend/components/shared/inputs/SelectInput.tsx
frontend/hooks/utilities.tsx

Ticket: https://govstack-global.atlassian.net/browse/TECH-1086
Changes: 
- Added smooth scroll to view select options on focus.

TECH-1086: scroll to display select options

---

frontend/__tests__/components/header/__snapshots__/Header.test.tsx.snap
frontend/__tests__/components/mainLayout/__snapshots__/MainLayout.test.tsx.snap
frontend/components/compliance/SoftwareDetails.less
frontend/components/form/SoftwareAttributesForm.tsx
frontend/components/header/Header.tsx
frontend/pages/data-protection-notice/index.tsx
frontend/pages/imprint/index.tsx
frontend/service/constants.ts
frontend/styles/Globals.less
frontend/translations/en.ts

Ticket: https://govstack-global.atlassian.net/browse/TECH-1089
Changes: 
- added new pages
- added template for imprint and data protection notice pages
- added disclaimer to the 1st step form

TECH-1089: add new pages, added disclaimer to form

---

README.md

Ticket:
https://govstack-global.atlassian.net/browse/TECH-1089

TECH-1089: updated readme file

---

frontend/components/shared/combined/SelectBBs.tsx

hotfix: fix ts type
