GovStackWorkingGroup/testing-webapp

- deployment/run-prod.sh
- docker-compose.override.yml
- docker-compose.yml
* Split developer volume mounts into an override file
* Regular compose file deploys the app same as on prod
* Added a script that updates git and starts in prod mode
This is probably not a long term solution, but for now it will keep our testing server automatically updated.
Next step is to use this in Circle CI.
> TECH-454: Script for automatic update of testing server

- server/src/controllers/reportController.js
- server/src/db/repositories/reportRepository.js
- server/src/repositories/reportRepository.js
- server/src/routes/record.js
- server/src/useCases/report/productCompatibility/handleGetProductRequest.js
- server/src/useCases/report/productCount/handleGetProductCountRequest.js
- server/src/useCases/report/productTestCases/handleGetProductDetailsRequest.js
Added endpoint to get bb details for a product. Response example:
**Description**:
Mock: https://www.figma.com/file/9XudBIl7YAt3aH1nMBoO4L/govstack?node-id=41%3A2210&t=xjFQf3YJda8qpGhc-0
Acceptance criteria:
it’s possible to send a request to get a list of tests
each test contains the necessary fields to display information from mock
request supports pagination
**TICKET**: https://govstack-global.atlassian.net/browse/TECH-409
> TECH-409: Add endpoint for building block in product (BE)

- server/src/routes/record.js
Fixed /report/count endpoint
Description:
/report/count endpoints returns error message:
_Unexpected exception occurred: BSONTypeError: Argument passed in must be a string of 12 bytes or a string of 24 hex
characters or an integer_
Acceptance criteria
- /report/count endpoint works as expected
- should return : 
{
"count": n
}
TICKET: https://govstack-global.atlassian.net/browse/TECH-522
> TECH-522:     TECH-271  TECH-522 Fix /report/count endpoint

- server/src/db/repositories/reportRepository.js
- server/src/routes/record.js
- server/src/useCases/report/productTestCases/handleGetProductDetailsRequest.js
Updated /report/:id endpoint to also return gherkin scenarios data. Removed reduce method from handler -> moved calculations from there to aggregation. 
```details``` example: 
TICKET: https://govstack-global.atlassian.net/browse/TECH-519
> TECH-519: Add gherkin scenarios steps data to report/:id endpoint (BE)

- server/src/db/repositories/reportRepository.js
**Description**:
Details are grouped by scenarios. Because of that, if scenario is not unique, its ‘steps’ are being stacked.
Acceptance criteria: 
- Steps does not stack for scenarios with the same name. Each scenario contain just own steps
TICKET: https://govstack-global.atlassian.net/browse/TECH-533
> TECH-533: Fix /report/:id endpoint

- .dockerignore
- docker-compose.override.yml
- server/.dockerignore
Missing node modules cause failure of overridden docker setup (nodemon and next not ofund).
> Fix node_modules in docker dev setup 

- server/Dockerfile
- server/package.json
- server/src/controllers/reportController.js
- server/src/db/schemas/report.js
- server/src/routes/record.js
- server/src/useCases/report/reportSave/handleSaveRequest.js
- server/yarn.lock
Part of [TECH-456](https://govstack-global.atlassian.net/browse/TECH-456)
Report upload was extended by additional META file field. 
It is not mandatory and content of newly created Report schema property `productMetaData` is replaced with artificial value baset on testApp value. 
[TECH-456]: https://govstack-global.atlassian.net/browse/TECH-456?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TECH-456: Added META.yml

- __tests__/components/table/mockedData/ProductTable.ts
- server/src/db/schemas/report.js
- server/src/useCases/report/productCompatibility/handleGetProductRequest.js
- server/src/useCases/report/reportSave/handleSaveRequest.js
- service/types.ts
Ticket
[TECH-790](https://govstack-global.atlassian.net/browse/TECH-790)
Test-utils PR:
https://github.com/GovStackWorkingGroup/test-utils/pull/9
Changes:
- added a version property to the report schema.
Testing Methodology:
- I have locally executed the tests for the bb-digital-registries project. All generated reports, based on the main branch, were successfully stored in the database. Additionally, each report now includes a version property that indicates the tag used.
[TECH-790]: https://govstack-global.atlassian.net/browse/TECH-790?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TECH-790: added versioning for test suite

- server/src/db/schemas/compliance.js
Ticket:
https://govstack-global.atlassian.net/browse/TECH-894
Key Features:
ComplianceDetailSchema: Represents individual compliance details.
- Contains specifications for a building block (bbSpecification).
- Tracks building block version (bbVersion).
- Holds status (defaulted to 'in review') and submission date.
- Deployment compliance, requirement specifications, and interface details are nested within.
ComplianceVersionSchema: A container to group building block details by version.
- Holds a version identifier.
- Uses a Map to associate building block names with their respective details.
ComplianceReportSchema: Represents the overarching compliance report for a piece of software.
- Contains metadata like software name, logo, website URL, documentation links, and point of contact.
- …
> TECH-894: draft version for content compliance schema

- backend/src/db/pipelines/compliance/softwareDetailAggregation.ts
**Changes:**
The pipeline for the aggregation of compliance form details has been modified within the scope of this ticket to accommodate multiple versions per building block without encountering key errors.
**New format of returned data:**
```
{
"logo": str,
"website": str,
"documentation": str,
"pointOfContact": str,
"softwareName": str
compliance: [
{	
softwareVersion: "1.0"
bbDetails: [	
{ bbName1: "bb-payments"
bbVersions: [
bbVersion: 1.1 bbDetail: {requirements, interface}
bbVersion: 1.2 bbDetail: {requirements, interface}
bbVersion: 2.1 bbDetail: {requirements, interface}
]},
{ bbName1: "bb-digital-registries"
bbVersions: [
bbVersion: 1.1 bbDetail: {requirements, interface}
bbVersion: 1.2 bbDetail: {requirements, interface}
bbVersion: 2.1 bbDetail: {requirements, interface}
]},
{ …
```
> TECH-891: Changed compliance detail pipeline to handle more version per bb

- backend/@types/index.d.ts
- backend/src/config/index.ts
- backend/src/db/repositories/complianceRepository.ts
- backend/src/useCases/compliance/handleSubmitForm.ts
Ticket:
https://govstack-global.atlassian.net/browse/TECH-901
Changes:
- changed Jira ticket creation to present this pattern:
```
SPACE - we’ll keep these in the TECH project for now
LABEL - create a new label called ‘Compliance’
ASSIGNEE - @Nico
TITLE - Compliance Form Submitted for <Product Name>
DESCRIPTION - <Product Name> has submitted a self-assessment for <Building Blocks>. View the submission at <Link to form in the testing harness>
Let me know if any of the data that I am suggesting here is not available to embed in the ticket. 
```
- fixed generated link for Jira TIcket
> TECH-901: changed Jira ticket creation, extended template

- backend/__tests__/gitBookApi.test.ts
- backend/src/services/gitBookService/CollectionsManager.ts
- backend/src/services/gitBookService/PageContentManager.ts
Ticket:
https://govstack-global.atlassian.net/browse/TECH-1011
Changes:
- version changed from semantic to yearQnumber (along with the sorting and fetch function)
- functional requirements now trim the text to get only short descriptive text
- functional requirements pattern is extended with headers-2
Test:
- manually revised 118 req fetched from paymets develop bb and around 50 from registration
> TECH-1011: functional requirements extended and version for bb changed

- frontend/components/form/IRSForm.tsx
- frontend/components/shared/combined/SelectBBs.tsx
- frontend/components/table/IRSC/IRSCCrossCuttingTable.tsx
- frontend/components/table/IRSC/IRSCFunctionalTable.tsx
- frontend/components/table/IRSC/IRSCInterfaceTable.tsx
Ticket: https://govstack-global.atlassian.net/browse/TECH-1028
> TECH-1028: Fix compliance form 3rd step fulfillemnt error

- backend/@types/index.d.ts
- backend/src/db/pipelines/compliance/AllbbRequirements.ts
- backend/src/db/pipelines/compliance/draftDetailAggregation.ts
- backend/src/db/pipelines/compliance/formDetailAggregation.ts
- backend/src/db/schemas/bbRequirements.ts
- backend/src/db/schemas/compliance/compliance.ts
- backend/src/services/gitBookService/KeyDigitalFunctionalitiesExtractor.ts
- backend/src/services/gitBookService/PageContentManager.ts
- backend/src/services/gitBookService/bbRequirementsProcessing.ts
**Ticket:**
https://govstack-global.atlassian.net/browse/TECH-1040
**Changes:**
- Key Digital Functionalities are fetched with functional and interface requirements when cron job is ran
- class PageContentManager is extended with new module designed for KDF
- KDF is added to GET FORM/DRAFT endpoint
- KDF is added to EDIT DRAFT endpoint
- KDF is fetched from each BB on gitbookapi with this approach:
```
1. Process Top-Level Headings:
1.1 The code starts by iterating through the nodes in the document.
1.2 If it encounters a heading that starts with "4." (e.g., "4.2 Core Services"), it processes this heading.
2. Handling Sections without Sub-Headers:
2.1 If a section does not contain any sub-headers but contains paragraphs or other text nodes, the entire section text is captured as a single …
```
> TECH-1040: Key Digital Functionalities are fetched from gitbook api

- backend/src/db/pipelines/compliance/softwareDetailAggregation.ts
- frontend/components/compliance/SoftwareDetails.tsx
- frontend/pages/requirements/details/[softwareName]/index.tsx
**Ticket:**
https://govstack-global.atlassian.net/browse/TECH-1054
**Changes:**
- if there is more than one draft then newest description of draft will be displayed
- building blocks will be listed for each version instead of one (as it was done before)
- list of reports IDs is stored instead of one inconsistent ID, each is handled properly with "view reports details" buttons
**Consistent description:**
**Handles each form:**
**How was it tested?**
1. Page display is now consistent and returns proper description every time
2. Empirical tests with 50 request on backend and aditional 30 on FE always provided the same result with latest software description
> feature/TECH-1054: consistent display of bb and description for each form

- backend/src/services/gitBookService/KeyDigitalFunctionalitiesExtractor.ts
- backend/src/services/gitBookService/PageContentManager.ts
Ticket:
https://govstack-global.atlassian.net/browse/TECH-1056
Changes:
- status of each ticket is not trimmed
- interface, cross-cutting and functional requirements has their status always on the start of the text
- KDF has always status (REQUIRED) on the start
Testing:
> TECH-1056: status is now displayed for each cross-cutting, functional and interface requirement

- frontend/components/table/IRSC/IRSCTable.less
- frontend/translations/en.ts
ticket: https://govstack-global.atlassian.net/browse/TECH-1042
and https://govstack-global.atlassian.net/browse/TECH-1048
Changes: 
- added white background to comment value columns, some browsers were using grey background for textarea
- changed first letter in ‘View report details’ as capital letter, it will look consistent to the rest of the system
> TECH-1042: Updates to 1042 and 1048 tickets.

- frontend/components/compliance/ReportViewDetail.tsx
- frontend/components/shared/combined/RequirementSpecificationSelectBB.tsx
- frontend/components/shared/combined/SelectBBs.tsx
- frontend/translations/en.ts
Ticket: https://govstack-global.atlassian.net/browse/TECH-1047
Changes: 
- Added placeholder to tabs with no content
- Fixed when refreshing details showed no content
> TECH-1047: Add placeholder text to empty assessment entries

- docker-compose.yml
- frontend/.gitignore
- frontend/content/template/data-protection-notice.html
- frontend/content/template/imprint.html
- frontend/pages/data-protection-notice/index.tsx
- frontend/pages/imprint/index.tsx
Ticket:
https://govstack-global.atlassian.net/browse/TECH-1089
Changes:
- docker now stores custom static pages
- pages displays custom context, and if it is not provided then default template
Test:
1. Locally worked for custom/default pages before and after rebuilding containers.
> TECH-1089: added default and custom static pages

- backend/src/db/repositories/complianceRepository.ts
Ticket:
https://govstack-global.atlassian.net/browse/TECH-1104
Changes:
- empty characters are trimmed form the end of the software name
Locally created name with input: "333              ". Server correctly created softwareName with proper name "333".
> TECH-1104: trimmed empty characters from the end of softwarename

- backend/src/db/pipelines/compliance/draftDetailAggregation.ts
In scope of this ticket empty value for functional Requirements was fixed.
1. New draft was created  and it properly sends back a functional requirements list with this endpoint.
Note:
1. It resolves issue with "mapping functional requirements error" but it does not resolve issue on already created document to display the functional requirements unless use change bb and adds it again.
> Hotfix: fixed typo in draft detail aggregation pipeline

- backend/server.ts
- backend/src/middlewares/fileUpload.ts
- frontend/components/form/SoftwareComplianceForm.tsx
- frontend/service/serviceAPI.ts
- frontend/service/types.ts
- frontend/translations/en.ts
Ticket:
https://govstack-global.atlassian.net/browse/TECH-1100
Changes:
- logo is limited to 1MB
- translation is added with information that logo is 1MB
- toast message with proper info is displayed when logo is too large
- updated handleSaveDraft and saveSoftwareDraft functions
Manually tested it creating a draft with too large logo.
> TECH-1100: logo file is limited up to 1MB, added toast message

- backend/src/services/gitBookService/KeyDigitalFunctionalitiesExtractor.ts
- frontend/components/form/SoftwareAttributesForm.tsx
- frontend/components/form/helpers.tsx
- frontend/components/shared/DragAndDrop.tsx
- frontend/translations/en.ts
Ticket:
https://govstack-global.atlassian.net/browse/TECH-1100
https://govstack-global.atlassian.net/browse/TECH-1092
Changes:
- for missing logo new error is introduced 'No file selected. Please choose a file to upload.' instead of info that the field is required
- introduce validation for file size
- simplified validation for types and size, allowing to extend it in the future if needed
- too large file is not being saved in the storage
- when file is no selected and user tries to save:
- when file is too large:
- when file is in wrong format:
- other uploads are not affected:
> TECH-1100: FE validation for files error handling
